### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by UncleRemis** [Cyclops789/rumble-notifier#2]
This doesn't actually do anything at all. It doesn't even install. "pip is not a valid command".

But even if I could get it installed, there's no way to use the webhook with my Discord bot.

What is this even for? It doesn't do anything.

**Comment by HamzaJarane** [comment]
- You will need to install python3 and pip3 package.
- Discord webhooks can be getting from a channel settings.

Learn the language before running any code 😛.
