### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by mobbyg** [Cyclops789/rumble-notifier#3]
When I try running the script, I am getting a connection reset error
![image](https://github.com/Cyclops789/rumble-notifier/assets/5174814/22ac78d0-f66d-48f3-9dfd-a3b9c95cfd5b)

Here is my config.yml. It's possible I don't have the correct info in there. 

`channel_link: "https://rumble.com/c/OttermanGamingEmpire"

webhook_video_username: "Otterman Gaming- Video"

webhook_live_username: "Otterman Gaming Empire - Live"

webhook_embed_color: "85c742"

webhooks_picture: "https://hugh.cdn.rumble.cloud/s/z8/l/P/L/v/lPLva.baa.2-OtterGaming-s9omnl.png"

webhook_live: URL from Discord for webhook

webhook_video: URL from Discord for webhook`

Am I missing something??

**Comment by HamzaJarane** [comment]
Hey @mobbyg, I rewrote the script in javascript since it became my main development stack, you can delete the project and reclone it again, make sure that "webhook_embed_color" is a valid hex color (starts with #).

**Comment by mobbyg** [comment]
Thanks! I'll give it a try!

**Comment by HamzaJarane** [comment]
> Thanks! I'll give it a try!

Your welcome! I will close this issue for now.
